# Lecture 4 — Arrays as Fields and Phase Space

**Goal:**  
Understand arrays as **discretised physical systems**, not just containers of numbers.

In physics:
- a list → many particles
- an array → a field
- indexing → spatial location or particle identity


## From Single Particle to Many Degrees of Freedom

So far we simulated:
- one particle
- one position
- one velocity

Real physics involves:
- many particles
- fields defined over space
- distributions in phase space

Arrays let us represent this numerically.


In [3]:
import numpy as np

## Why Arrays Instead of Lists?

Python lists:
- flexible
- slow for numerical physics

NumPy arrays:
- fixed size
- homogeneous (same type)
- vectorised (operate on all elements at once)

This is why NumPy dominates computational physics.


In [4]:
x_list = [0, 1, 2, 3, 4]
x_array = np.array(x_list)

x_array


array([0, 1, 2, 3, 4])

## Arrays as Discretised Space

Consider a 1D spatial grid:
\[
x_i = x_0 + i\,\Delta x
\]

We approximate continuous space with discrete points.


In [5]:
x = np.linspace(0, 10, 101)  # 0 to 10 m, 101 grid points
dx = x[1] - x[0]

x[:5], dx


(array([0. , 0.1, 0.2, 0.3, 0.4]), np.float64(0.1))

## Fields on a Grid

A scalar field:
- temperature
- density
- potential

is represented as an array with one value per grid point.


In [6]:
# Temperature field (arbitrary example)
T = 300 + 50 * np.sin(2 * np.pi * x / 10)

T[:5]


array([300.        , 303.13952598, 306.26666168, 309.36906573,
       312.43449436])

## Vectorisation = Apply Physics Everywhere

This line:
```python
T = 300 + 50 * np.sin(2 * np.pi * x / 10)



---

## 🟩 Code Cell 5 — Compare Loop vs Vectorisation
```python
# Loop version
T_loop = np.zeros_like(x)
for i in range(len(x)):
    T_loop[i] = 300 + 50 * np.sin(2 * np.pi * x[i] / 10)

np.allclose(T, T_loop)


## Phase Space: Position + Velocity

In mechanics, a system state is:
\[
(x, v)
\]

For many particles:
- positions → array
- velocities → array

Together, they define **phase space**.


In [7]:
N = 100

# Random initial positions and velocities
x = np.random.uniform(0, 10, N)
v = np.random.normal(0, 1, N)

x[:5], v[:5]


(array([9.24659399, 4.08397034, 2.12582919, 7.73065237, 1.12112474]),
 array([ 0.40971897, -0.0869875 ,  1.71388044, -0.47500822, -0.80665539]))

## Evolving Phase Space

Using Euler integration:
\[
x_{n+1} = x_n + v_n \Delta t
\]

All particles update simultaneously using arrays.


In [8]:
dt = 0.01
x = x + v * dt

x[:5]


array([9.25069118, 4.08310047, 2.142968  , 7.72590229, 1.11305819])

## Forces Acting on Many Particles

Example: harmonic oscillator
\[
F = -kx
\quad\Rightarrow\quad
a = -kx/m
\]

Force and acceleration become array operations.


In [9]:
k = 1.0
m = 1.0

a = -k * x / m
v = v + a * dt


## Conditional Indexing = Physics Selection

We often want to apply physics only in certain regions:
- density thresholds
- temperature cuts
- spatial masks

NumPy allows **conditional indexing**.


In [10]:
# Particles with positive position
mask = x > 5

mask[:10]


array([ True, False, False,  True, False,  True,  True, False,  True,
        True])

In [ ]:
# Apply force only where x > 5
v[mask] *= 0.9

: 

## Big Picture

You have now seen arrays used as:
- spatial grids
- scalar fields
- particle ensembles
- phase-space representations

This is the foundation of:
- fluid dynamics
- plasma physics
- N-body simulations
- radiative transfer


## Common Pitfalls

1. Confusing list vs array behavior
2. Forgetting arrays operate element-wise
3. Shape mismatches
4. Accidental broadcasting

Always check:
```python
array.shape



---

## 🟩 Code Cell 10 — Shape Awareness
```python
x.shape, v.shape


# ✍️ Exercises

## Exercise A — Field Construction
Create a spatial grid from 0 to 1.
Define a density field:
\[
\rho(x) = \exp(-x^2)
\]

---

## Exercise B — Many-Particle Gravity (1D)
Simulate N particles under:
\[
a = -GM / x^2
\]
(use a softening term to avoid division by zero).

---

## Exercise C — Phase Space Thinking
Store:
- positions
- velocities
- energies

as arrays and evolve them together.


## What You Learned

- Arrays represent **many degrees of freedom**
- Vectorisation applies physics everywhere at once
- Fields and phase space are numerical arrays
- This is how simulations scale from 1 to millions of elements
